module.exports = (sequelize, DataTypes) => {
  return sequelize.define(
    "ItemSalePayment",
    {
      isp_id: { type: DataTypes.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true },
      br_id: DataTypes.INTEGER.UNSIGNED,
      is_id: DataTypes.INTEGER.UNSIGNED,
      isp_type: DataTypes.ENUM("Cash", "Card", "CashCard", "Signed", "Voucher", "Entertainment", "DownPayment"),
      ct_id: DataTypes.INTEGER.UNSIGNED,
      ct_id_detected: DataTypes.INTEGER.UNSIGNED,
      cc_id: DataTypes.INTEGER.UNSIGNED,
      v_id: DataTypes.INTEGER.UNSIGNED,
      be_id: DataTypes.INTEGER.UNSIGNED,
      dt_id: DataTypes.INTEGER.UNSIGNED,
      ce_id: DataTypes.INTEGER.UNSIGNED,
      dp_id: DataTypes.INTEGER.UNSIGNED,
      dp_type: DataTypes.INTEGER.UNSIGNED,
      isp_card_number: DataTypes.STRING(20),
      isp_card_holder: DataTypes.STRING(30),
      isp_signer_name: DataTypes.STRING(20),
      isp_voucher_number: DataTypes.STRING(32),
      isp_trace_num: DataTypes.STRING(32),
      isp_appr_code: DataTypes.STRING(32),
      isp_rrn: DataTypes.STRING(32),
      isp_voucher_value: DataTypes.DECIMAL(12, 2),
      isp_tendered: DataTypes.DECIMAL(12, 2),
      isp_rate: DataTypes.DECIMAL(12, 2),
      isp_change: DataTypes.DECIMAL(12, 2),
      isp_rounding: DataTypes.DECIMAL(5, 2),
      isp_card_issuer: DataTypes.INTEGER.UNSIGNED,
      isp_amount: DataTypes.DECIMAL(12, 2),
      isp_paid: DataTypes.ENUM("False", "True"),
      isp_paid_date: DataTypes.DATE,
      isp_entry: DataTypes.DATE,
      isp_deletion: DataTypes.DATE,
      isp_status: DataTypes.ENUM("Deleted", "Suspended", "Active"),
    },
    { tableName: "item_sale_payment", timestamps: false },
  );
};
