module.exports = (sequelize, DataTypes) => {
  return sequelize.define(
    "LogPrint",
    {
      lp_id: { type: DataTypes.INTEGER.UNSIGNED, primaryKey: true, autoIncrement: true },
      br_id: DataTypes.INTEGER.UNSIGNED,
      u_id: DataTypes.INTEGER.UNSIGNED,
      is_id: DataTypes.INTEGER.UNSIGNED,
      o_id: DataTypes.INTEGER.UNSIGNED,
      t_id: DataTypes.INTEGER.UNSIGNED,
      ts_id: DataTypes.INTEGER.UNSIGNED,
      ta_id: DataTypes.INTEGER.UNSIGNED,
      lp_print_type: DataTypes.ENUM("Order", "OrderReprint", "Receipt", "Area", "Bill", "Final", "Cancellation", "BillReprint", "VoidBill", "Other"),
      lp_title: DataTypes.STRING(100),
      lp_message: DataTypes.TEXT,
      lp_message_source: DataTypes.TEXT,
      lp_message_script: DataTypes.TEXT,
      lp_printer_name: DataTypes.STRING(16),
      lp_print_counter: DataTypes.INTEGER,
      lp_count: DataTypes.INTEGER.UNSIGNED,
      lp_time: DataTypes.DATE,
      lp_ip: DataTypes.STRING(15),
      pos_id: DataTypes.STRING(15),
      lp_printed: DataTypes.ENUM("False", "True"),
      lp_rpm_printed: DataTypes.ENUM("False", "True"),
      lp_print_time: DataTypes.DATE,
      lp_loaded: DataTypes.ENUM("False", "True"),
      lp_load_time: DataTypes.DATE,
      lp_redirected: DataTypes.ENUM("False", "True"),
      lp_redirect_time: DataTypes.DATE,
      lp_delayed_print: DataTypes.ENUM("False", "True"),
      lp_rpm_session: DataTypes.STRING(8),
    },
    { tableName: "log_print", timestamps: false },
  );
};
